name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tf-web-model:latest

    - name: Tag the image with timestamp
      run: |
        TIMESTAMP=$(date +%s)
        docker tag tf-web-model:latest ${{ secrets.DOCKER_USERNAME }}/tf-web-model:latest
        docker tag tf-web-model:latest ${{ secrets.DOCKER_USERNAME }}/tf-web-model:$(date +%s)
        echo "IMAGE_TAG=$TIMESTAMP" >> $GITHUB_ENV


    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/tf-web-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/tf-web-model:${{ env.IMAGE_TAG }}
