name: Docker Image CI

on:
  push:
    branches: [ "feature/initial" ]
  pull_request:
    branches: [ "feature/initial" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tf-web-model:$(date +%s)
